### ISSUE TITLE
Why I can only create Geometry<'static>?

### ISSUE THREAD

**Issue by ManeraKai** [georust/geos#152]
This is what I want
```rust
use geos::Geometry;
fn point() -> Geometry {
    let r = Geometry::create_empty_point().unwrap();
    r
}
```
but it's forcing me to have it 'static
```rust
use geos::Geometry;
fn point() -> Geometry<'static> {
    let r = Geometry::create_empty_point().unwrap();
    r
}
```
I don't want it to be static. I want to free it from memory after I finish. It's giving me memory leaks.

**Comment by GuillaumeGomez** [comment]
It's an issue indeed. Not sure why the lifetime is needed here...

**Comment by ManeraKai** [comment]
I think removing the lifetimes will resolve it: https://github.com/georust/geos/commit/83c32190fd253fb3459f2746d89b1906e671d79c

**Comment by GuillaumeGomez** [comment]
PR welcome. :)
