### ISSUE TITLE
Change the name of the method `to_wkt_precison` to `to_wkt_precision` ?

### ISSUE THREAD

**Issue by mthh** [georust/geos#20]
I made a silly typo in this commit : 42212ed.
Should we change the name of the method to the more explicit "to_wkt_precis**i**on" ?
I guess it's also a change in the API that would require incrementing the major version number.

**Comment by antoine-de** [comment]
Yes I think we should change the name and bump the version number as a breaking change (the minor one would be enough I think (`2.1.1`))
