### ISSUE TITLE
create a PreparedGeometry<'static> from a Geometry<'static> and dropping the latter makes the first unusable

### ISSUE THREAD

**Issue by gauteh** [georust/geos#86]
Seems like the PreparedGeometry should have a lifetime dependency on the original Geometry. When I try to use the the PreparedGeometry after dropping the original one I get various errors and sigabrts, including messages like `pure virtual method called` (which could have been a coincidence).

**Comment by GuillaumeGomez** [comment]
Thanks a lot!

**Comment by gauteh** [comment]
See: https://github.com/georust/geos/pull/87

**Comment by GuillaumeGomez** [comment]
Perfect, thanks! Going to send fix as soon as possible.

**Comment by gauteh** [comment]
I am trying to change my code to use these changes. As I want to avoid running `to_prepared_geometry` every time I am now in trouble. I cannot easily store both the geometry and the preparedgeometry in the same struct. But I wonder if this is actually safe after all: the geometry-data is perhaps heap-allocated or pinned anyway, making it safe to move the geometry around? Any suggestions for how to set that up? What I'm trying to do now is:

```
struct Foo<'a> {
  g: Geometry<'a>,
  p: PreparedGeometry<'a>
}

but I'm not getting it right...

**Comment by gauteh** [comment]
Something that works, but can be done much better: https://github.com/gauteh/roaring-landmask/pull/2/files#diff-7287b746975aadc977a38a86ee3163de1d9030d2902e510ba9d955e5f9b6f3c1R35

**Comment by GuillaumeGomez** [comment]
Try with:

```rust
struct Foo<'a, 'b: 'a> {
  g: Geometry<'b>,
  p: PreparedGeometry<'a>
}
```

?

**Comment by gauteh** [comment]
Thanks a lot! I'm still not allowed to move geom. But I removed the Pin stuff. I don't think the Pin would fix that error anyway, but make it a bit more sound.

https://github.com/gauteh/roaring-landmask/blob/pin-geom/src/shapes.rs#L35

**Comment by GuillaumeGomez** [comment]
You just found out one of the limits of the borrow checker: it doesn't allow a field a have a lifetime related to another field from the same type. :)

For now, the `transmute` is fine I guess.

**Comment by gauteh** [comment]
Ok, thanks :)
